### ISSUE TITLE
Add a routing feature

### ISSUE THREAD

**Issue by exKAZUu** [WillingRing/SimpleChat#7]
## Requirements
- Users can access the page of each room via a specific URL
  - e.g. http://localhost:3000/rooms/room_1
- Use `flow-router` to support the above routing feature

**Comment by CaptainYANG** [comment]
@exKAZUu I'm wondering if it's better to use the room name in the url like slack, or it's better to use the id room_1

**Comment by exKAZUu** [comment]
I believe that `_id` property of `Room` object is the best because `roomName` may include illegal characters for URL and allows duplicated values.
